import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import sys
import os
from pathlib import Path


class StatisticalAnalyzer:
    """
    A class to perform statistical analysis on CSV data with 2 columns.
    Calculates mean, std dev, SEM, 95% CI, generates synthetic data,
    and creates visualizations.
    """

    def __init__(self, csv_file):
        """Initialize with CSV file path."""
        self.csv_file = csv_file
        self.data = None
        self.column_names = []
        self.statistics = {}
        self.synthetic_data = {}

        # Create output folder based on input CSV name
        self.output_dir = self._create_output_folder()

    def _create_output_folder(self):
        """Create output folder named 'output_<csv_name_without_extension>'."""
        # Get CSV filename without extension
        csv_name = Path(self.csv_file).stem  # Gets filename without extension
        output_folder = f"output_{csv_name}"

        # Create folder if it doesn't exist
        Path(output_folder).mkdir(exist_ok=True)

        return output_folder

    def load_data(self):
        """Load CSV data."""
        try:
            self.data = pd.read_csv(self.csv_file)
            if len(self.data.columns) != 2:
                raise ValueError(f"CSV must have exactly 2 columns, found {len(self.data.columns)}")
            self.column_names = list(self.data.columns)
            print(f"Data loaded successfully from {self.csv_file}")
            print(f"Columns: {self.column_names}")
            print(f"Number of data points: {len(self.data)}")
            return True
        except Exception as e:
            print(f"Error loading data: {e}")
            return False

    def calculate_statistics(self):
        """Calculate mean, std dev, SEM, and 95% CI for both columns."""
        for col in self.column_names:
            values = self.data[col].dropna()
            n = len(values)

            # Calculate basic statistics
            mean = np.mean(values)
            std_dev = np.std(values, ddof=1)  # Sample standard deviation
            sem = std_dev / np.sqrt(n)  # Standard Error of Mean

            # Calculate 95% confidence interval using Student's t-distribution
            confidence_level = 0.95
            alpha = 1 - confidence_level
            df = n - 1  # degrees of freedom
            t_critical = stats.t.ppf(1 - alpha/2, df)

            # Error bar (half-width of CI)
            error_bar = t_critical * sem
            ci_lower = mean - error_bar
            ci_upper = mean + error_bar

            self.statistics[col] = {
                'n': n,
                'mean': mean,
                'std_dev': std_dev,
                'sem': sem,
                't_critical': t_critical,
                'error_bar': error_bar,
                'ci_lower': ci_lower,
                'ci_upper': ci_upper
            }

        return self.statistics

    def generate_synthetic_data(self, n_points=1000):
        """Generate synthetic data points using normal distribution."""
        for col in self.column_names:
            mean = self.statistics[col]['mean']
            std_dev = self.statistics[col]['std_dev']

            # Generate synthetic data from normal distribution
            synthetic = np.random.normal(mean, std_dev, n_points)
            self.synthetic_data[col] = synthetic

        print(f"\nGenerated {n_points} synthetic data points for each column")
        return self.synthetic_data

    def print_statistics(self):
        """Print statistics in a formatted way."""
        print("\n" + "="*70)
        print("STATISTICAL ANALYSIS RESULTS")
        print("="*70)

        for col in self.column_names:
            stats_dict = self.statistics[col]
            print(f"\n{col}:")
            print(f"  Sample size (n):              {stats_dict['n']}")
            print(f"  Mean (x-bar):                 {stats_dict['mean']:.6f}")
            print(f"  Standard Deviation (s):       {stats_dict['std_dev']:.6f}")
            print(f"  Standard Error of Mean (SEM): {stats_dict['sem']:.6f}")
            print(f"  t-critical (95% CI):          {stats_dict['t_critical']:.6f}")
            print(f"  Error Bar (+-):               {stats_dict['error_bar']:.6f}")
            print(f"  95% CI:                       [{stats_dict['ci_lower']:.6f}, {stats_dict['ci_upper']:.6f}]")

        print("\n" + "="*70)

    def generate_latex_output(self, output_file='latex_output.tex'):
        """Generate LaTeX formatted output for the statistics."""
        output_file = os.path.join(self.output_dir, output_file)

        latex_content = r"""\documentclass{article}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{geometry}
\geometry{margin=1in}

\title{Statistical Analysis Report}
\author{Generated by StatisticalAnalyzer}
\date{\today}

\begin{document}

\maketitle

\section{Statistical Summary}

"""

        # Add statistics table
        latex_content += r"""\begin{table}[h]
\centering
\caption{Statistical Analysis Results}
\begin{tabular}{lcc}
\toprule
Statistic & """ + self.column_names[0] + r""" & """ + self.column_names[1] + r""" \\
\midrule
"""

        # Add rows
        latex_content += f"Sample size ($n$) & {self.statistics[self.column_names[0]]['n']} & {self.statistics[self.column_names[1]]['n']} \\\\\n"
        latex_content += f"Mean ($\\bar{{x}}$) & {self.statistics[self.column_names[0]]['mean']:.6f} & {self.statistics[self.column_names[1]]['mean']:.6f} \\\\\n"
        latex_content += f"Std. Deviation ($s$) & {self.statistics[self.column_names[0]]['std_dev']:.6f} & {self.statistics[self.column_names[1]]['std_dev']:.6f} \\\\\n"
        latex_content += f"SEM & {self.statistics[self.column_names[0]]['sem']:.6f} & {self.statistics[self.column_names[1]]['sem']:.6f} \\\\\n"
        latex_content += f"$t_{{\\text{{critical}}}}$ (95\\%) & {self.statistics[self.column_names[0]]['t_critical']:.6f} & {self.statistics[self.column_names[1]]['t_critical']:.6f} \\\\\n"
        latex_content += f"Error Bar ($\\pm$) & {self.statistics[self.column_names[0]]['error_bar']:.6f} & {self.statistics[self.column_names[1]]['error_bar']:.6f} \\\\\n"

        latex_content += r"""\bottomrule
\end{tabular}
\end{table}

"""

        # Add confidence intervals
        latex_content += r"""\section{95\% Confidence Intervals}

"""
        for col in self.column_names:
            ci_lower = self.statistics[col]['ci_lower']
            ci_upper = self.statistics[col]['ci_upper']
            mean = self.statistics[col]['mean']
            error = self.statistics[col]['error_bar']

            latex_content += f"For \\textbf{{{col}}}:\n"
            latex_content += f"$$\\bar{{x}} \\pm \\text{{Error}} = {mean:.6f} \\pm {error:.6f}$$\n"
            latex_content += f"$$\\text{{CI}}_{{{0.95}}} = [{ci_lower:.6f}, {ci_upper:.6f}]$$\n\n"

        latex_content += r"""\section{Methodology}

The 95\% confidence interval was calculated using Student's $t$-distribution:

$$\text{Error Bar} = t_{\alpha/2, n-1} \times \text{SEM}$$

where:
\begin{itemize}
    \item $t_{\alpha/2, n-1}$ is the critical value from Student's $t$-distribution
    \item $\alpha = 0.05$ for 95\% confidence level
    \item $n-1$ is the degrees of freedom
    \item $\text{SEM} = \frac{s}{\sqrt{n}}$ is the Standard Error of the Mean
\end{itemize}

The confidence interval is then:
$$\text{CI} = \bar{x} \pm \text{Error Bar}$$

\end{document}
"""

        # Write to file
        with open(output_file, 'w') as f:
            f.write(latex_content)

        print(f"\nLaTeX output saved to: {output_file}")
        return latex_content

    def create_scatter_plot(self, output_file='scatter_plot.png', show_synthetic=True, dpi=300):
        """Create scatter plot with error bars."""
        output_file = os.path.join(self.output_dir, output_file)

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

        col_x, col_y = self.column_names

        # Left plot: Original data
        ax1.scatter(self.data[col_x], self.data[col_y], alpha=0.6, s=50,
                   label='Original Data', color='blue', edgecolors='black', linewidth=0.5)

        # Add error bars at mean position
        mean_x = self.statistics[col_x]['mean']
        mean_y = self.statistics[col_y]['mean']
        error_x = self.statistics[col_x]['error_bar']
        error_y = self.statistics[col_y]['error_bar']

        ax1.errorbar(mean_x, mean_y, xerr=error_x, yerr=error_y,
                    fmt='rs', markersize=10, capsize=5, capthick=2,
                    label='Mean ± 95% CI', linewidth=2)

        ax1.set_xlabel(f'{col_x}', fontsize=12, fontweight='bold')
        ax1.set_ylabel(f'{col_y}', fontsize=12, fontweight='bold')
        ax1.set_title('Original Data with Error Bars', fontsize=14, fontweight='bold')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # Right plot: Synthetic data
        if show_synthetic and self.synthetic_data:
            ax2.scatter(self.synthetic_data[col_x], self.synthetic_data[col_y],
                       alpha=0.3, s=20, label='Synthetic Data (n=1000)',
                       color='green', edgecolors='none')

            # Add mean with error bars
            ax2.errorbar(mean_x, mean_y, xerr=error_x, yerr=error_y,
                        fmt='rs', markersize=10, capsize=5, capthick=2,
                        label='Mean ± 95% CI', linewidth=2)

            ax2.set_xlabel(f'{col_x}', fontsize=12, fontweight='bold')
            ax2.set_ylabel(f'{col_y}', fontsize=12, fontweight='bold')
            ax2.set_title('Synthetic Data with Error Bars', fontsize=14, fontweight='bold')
            ax2.legend()
            ax2.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.savefig(output_file, dpi=dpi, bbox_inches='tight')
        print(f"Scatter plot saved to: {output_file}")
        plt.close()

    def create_candlestick_plot(self, output_file='candlestick_plot.png', dpi=300):
        """Create candlestick-style plot with error bars for both columns."""
        output_file = os.path.join(self.output_dir, output_file)

        fig, ax = plt.subplots(figsize=(10, 8))

        positions = [1, 2]
        colors = ['steelblue', 'coral']

        for i, col in enumerate(self.column_names):
            stats_dict = self.statistics[col]
            mean = stats_dict['mean']
            error = stats_dict['error_bar']
            std = stats_dict['std_dev']
            ci_lower = stats_dict['ci_lower']
            ci_upper = stats_dict['ci_upper']

            # Draw the box (representing ±1 std dev from mean)
            box_bottom = mean - std
            box_top = mean + std
            box_height = 2 * std

            # Create box
            box = plt.Rectangle((positions[i] - 0.3, box_bottom), 0.6, box_height,
                               facecolor=colors[i], alpha=0.6, edgecolor='black', linewidth=2)
            ax.add_patch(box)

            # Draw mean line
            ax.plot([positions[i] - 0.3, positions[i] + 0.3], [mean, mean],
                   'k-', linewidth=3, label='Mean' if i == 0 else '')

            # Draw error bars (95% CI)
            ax.errorbar(positions[i], mean, yerr=error, fmt='none',
                       color='darkred', capsize=10, capthick=3, linewidth=3,
                       label='95% CI' if i == 0 else '')

            # Draw whiskers (min/max of data)
            data_min = self.data[col].min()
            data_max = self.data[col].max()
            ax.plot([positions[i], positions[i]], [box_top, data_max], 'k-', linewidth=1.5)
            ax.plot([positions[i], positions[i]], [box_bottom, data_min], 'k-', linewidth=1.5)
            ax.plot([positions[i] - 0.15, positions[i] + 0.15], [data_max, data_max], 'k-', linewidth=1.5)
            ax.plot([positions[i] - 0.15, positions[i] + 0.15], [data_min, data_min], 'k-', linewidth=1.5)

            # Add text annotations
            ax.text(positions[i], mean, f'{mean:.3f}',
                   ha='center', va='bottom', fontsize=9, fontweight='bold')
            ax.text(positions[i] + 0.35, ci_upper, f'{ci_upper:.3f}',
                   ha='left', va='center', fontsize=8, color='darkred')
            ax.text(positions[i] + 0.35, ci_lower, f'{ci_lower:.3f}',
                   ha='left', va='center', fontsize=8, color='darkred')

        ax.set_xticks(positions)
        ax.set_xticklabels(self.column_names, fontsize=12, fontweight='bold')
        ax.set_ylabel('Value', fontsize=12, fontweight='bold')
        ax.set_title('Candlestick Plot with 95% CI Error Bars', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3, axis='y')
        ax.legend(loc='best', fontsize=10)

        # Add text box with statistics
        textstr = 'Box: Mean ± 1 SD\nWhiskers: Min/Max\nError bars: 95% CI'
        props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
        ax.text(0.02, 0.98, textstr, transform=ax.transAxes, fontsize=10,
               verticalalignment='top', bbox=props)

        plt.tight_layout()
        plt.savefig(output_file, dpi=dpi, bbox_inches='tight')
        print(f"Candlestick plot saved to: {output_file}")
        plt.close()

    def save_text_summary(self, output_file='summary.txt'):
        """Save a plain-text summary of the analysis into the output folder."""
        output_file = os.path.join(self.output_dir, output_file)

        lines = []
        lines.append("=" * 70)
        lines.append("STATISTICAL ANALYSIS SUMMARY")
        lines.append("=" * 70)
        lines.append(f"Source CSV : {self.csv_file}")
        lines.append(f"Columns   : {self.column_names}")
        lines.append(f"Data pts  : {len(self.data)}")
        lines.append("")

        for col in self.column_names:
            s = self.statistics[col]
            lines.append(f"{col}:")
            lines.append(f"  Sample size (n)              : {s['n']}")
            lines.append(f"  Mean (x-bar)                 : {s['mean']:.6f}")
            lines.append(f"  Standard Deviation (s)       : {s['std_dev']:.6f}")
            lines.append(f"  Standard Error of Mean (SEM) : {s['sem']:.6f}")
            lines.append(f"  t-critical (95% CI)          : {s['t_critical']:.6f}")
            lines.append(f"  Error Bar (+-)               : {s['error_bar']:.6f}")
            lines.append(f"  95% CI                       : [{s['ci_lower']:.6f}, {s['ci_upper']:.6f}]")
            lines.append("")

        lines.append("=" * 70)
        lines.append("Synthetic data: 1000 points per column (Normal distribution)")
        lines.append("=" * 70)
        lines.append("")
        lines.append("Output files in this folder:")
        lines.append("  scatter_plot.png      - Scatter plot (original + synthetic)")
        lines.append("  candlestick_plot.png  - Candlestick plot with error bars")
        lines.append("  latex_output.tex      - LaTeX formatted report")
        lines.append("  summary.txt           - This file")
        lines.append("")

        text = "\n".join(lines)
        with open(output_file, 'w') as f:
            f.write(text)
        print(f"Text summary saved to: {output_file}")

    def run_full_analysis(self, generate_plots=True, generate_latex=True):
        """Run complete analysis pipeline."""
        print("\n" + "="*70)
        print("STARTING STATISTICAL ANALYSIS")
        print("="*70)
        print(f"Output folder: {os.path.abspath(self.output_dir)}")
        print("="*70)

        # Load data
        if not self.load_data():
            return False

        # Calculate statistics
        self.calculate_statistics()
        self.print_statistics()

        # Generate synthetic data
        self.generate_synthetic_data(n_points=1000)

        # Generate all outputs into the output folder
        if generate_latex:
            self.generate_latex_output()

        if generate_plots:
            self.create_scatter_plot()
            self.create_candlestick_plot()

        self.save_text_summary()

        print("\n" + "="*70)
        print("ANALYSIS COMPLETE!")
        print(f"All outputs saved to: {os.path.abspath(self.output_dir)}")
        print("="*70)
        return True


def main():
    """Main function to run the analysis."""
    if len(sys.argv) < 2:
        print("Usage: python statistical_analysis.py <csv_file>")
        print("\nExample CSV format:")
        print("Column1,Column2")
        print("1.2,3.4")
        print("2.3,4.5")
        print("...")

        # Create example CSV
        print("\nCreating example CSV file: example_data.csv")
        example_data = pd.DataFrame({
            'Temperature': np.random.normal(25, 2, 50),
            'Pressure': np.random.normal(100, 5, 50)
        })
        example_data.to_csv('example_data.csv', index=False)
        print("Example CSV created. Run: python statistical_analysis.py example_data.csv")
        return

    csv_file = sys.argv[1]

    # Create analyzer and run analysis
    analyzer = StatisticalAnalyzer(csv_file)
    analyzer.run_full_analysis()


if __name__ == "__main__":
    main()

